name: Multi Event Workflow
on:
  issue_comment:
    types: [created, edited, deleted]
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  # issue_comment
  pr_commented:
    # pr comments에만 run
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}

  issue_commented:
    # issue comments에만 run
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
  
  # pull_request
  pr-opened:
    if: ${{ github.event.action == 'opened'}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR opened"
  
  pr-reopened:
    if: ${{ github.event.action == 'reopened'}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR reopened"        
  
  # workflow-dispatch
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
