name: Needs Workflow
on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job 1 running."

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "Job 2 running after Job 1."

  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - run: echo "Job 3 running after Job 1 and Job 2."
